### ISSUE TITLE
total - плохое название для функции (ни о чём не говорит)

### ISSUE THREAD

**Issue by coursar** [brotik/webrulons#2]
https://github.com/brotik/homework/blob/80eb09e0f10500a6bc19819b0e927906750de383/lib_for_HW2.py#L2

**Comment by brotik** [comment]
Исправлено
https://github.com/brotik/homework/blob/80eb09e0f10500a6bc19819b0e927906750de383/lib_for_HW2.py#L2

Cм. #2

**Comment by coursar** [comment]
![screenshot from 2019-02-13 11-47-24](https://user-images.githubusercontent.com/3601892/52698733-33ef7e00-2f85-11e9-9e34-fe92147daf2a.png)
![screenshot from 2019-02-13 11-47-36](https://user-images.githubusercontent.com/3601892/52698739-37830500-2f85-11e9-8ca5-86bb82aeec14.png)
