### ISSUE TITLE
Magic Constants: 0.1 и 1.06

### ISSUE THREAD

**Issue by coursar** [brotik/webrulons#3]
Нужно вынести в переменные с говорящими именами

https://github.com/brotik/homework/blob/80eb09e0f10500a6bc19819b0e927906750de383/lib_for_HW2.py#L14-L15

**Comment by brotik** [comment]
Не совсем понял
так?
ширина рулона = 1.06
запас = 0.1

**Comment by coursar** [comment]
да, только переменные надо называть на английском

**Comment by brotik** [comment]
готово

**Comment by coursar** [comment]
Если готово - нужно закрывать issue, а не переназначать на меня
